name: Auto Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
    - uses: game-ci/unity-test-runner@v3
    env:
      UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
    with:
      projectPath: Jacks Fps Test/
      githubToken: ${{ secrets.GITHUB_TOKEN }}
